#!/bin/bash

# if all the files exist, then skip the creation
if [ -f ".env" ] && [ -f ".env-dev" ] && [ -f ".env-dev-docker" ]; then
  exit 0
fi

# Prompt the user for the BBB server domain
read -p "Enter the domain where your BBB server is hosted (e.g., example.com): " DOMAIN

# Prompt the user for the BBB secret
read -p "Enter the BBB secret: " SECRET

# Whisper model size (tiny, tiny.en, small, small.en, base, base.en, medium, medium.en, large-v1, large-v2, large-v3)
read -p "Enter the whisper model size (tiny, small, base, medium, large): " WHISPER_MODEL_SIZE

create_file_if_not_exists() {
  local file_name="$1"
  local content="$2"

  if [ -f "$file_name" ]; then
    echo "File '$file_name' already exists. Skipping creation."
  else
    echo "$content" > "$file_name"
    echo "File '$file_name' created."
  fi
}

# Generate the .env file. This will be used by docker (docker-compose.yaml)
ENV_CONTENT=$(cat <<EOF
BBB_API_URL="https://$DOMAIN/bigbluebutton/api/"
BBB_API_SECRET="$SECRET"
BBB_API_SHA="SHA256"

BBB_CLIENT_URL="https://$DOMAIN/html5client/"
BBB_CLIENT_WS="wss://$DOMAIN/html5client/websocket"

BBB_PAD_URL="https://$DOMAIN/pad/"
BBB_PAD_WS="wss://$DOMAIN/pad/"

BBB_WEBRTC_WS="wss://$DOMAIN/bbb-webrtc-sfu"

CHANGESET_EXTERNAL="true"
CHANGESET_HOST="changeset-service"
CHANGESET_PORT="50051"

TRANSCRIPTION_SERVER_HOST="0.0.0.0"
TRANSCRIPTION_SERVER_EXTERNAL_HOST="transcription-service"
TRANSCRIPTION_SERVER_PORT_TCP="5000"
TRANSCRIPTION_SERVER_PORT_UDP="5001"
TRANSCRIPTION_SERVER_SECRET="your_secret_token"
TRANSCRIPTION_SERVER_HEALTH_CHECK_PORT="8001"
TRANSCRIPTION_SERVER_PROMETHEUS_PORT="2112"
TRANSCRIPTION_AUDIO_BUFFER_LAST_N_SECONDS="30"
TRANSCRIPTION_AUDIO_BUFFER_MIN_N_SECONDS="1"
TRANSCRIPTION_RATE_LIMITER_FLOWRATE_PER_SECOND="2.0"
TRANSCRIPTION_CONVERT_AUDIO_CONVERT_SAMPLE_RATE="16000"
TRANSCRIPTION_VAD_DEVICE="cuda"
TRANSCRIPTION_VAD_MODEL_PATH="/app/.models/vad-whisperx"
TRANSCRIPTION_VAD_MAX_CHUNK_SIZE="30.0"
TRANSCRIPTION_VAD_LAST_TIME_SPOKEN_OFFSET="3"
TRANSCRIPTION_VAD_ONSET="0.500"
TRANSCRIPTION_VAD_OFFSET="0.363"
TRANSCRIPTION_VAD_USE_AUTH_TOKEN=""
TRANSCRIPTION_VAD_MODEL_FP=""
TRANSCRIPTION_VAD_SEGMENTATION_URL="https://whisperx.s3.eu-west-2.amazonaws.com/model_weights/segmentation/0b5b3216d60a2d32fc086b47ea8c67589aaeb26b7e07fcbe620d6d0b83e209ea/pytorch_model.bin"
TRANSCRIPTION_FASTER_WHISPER_MODEL_PATH="/app/.models/faster-whisper"
TRANSCRIPTION_FASTER_WHISPER_MODEL_SIZE="$WHISPER_MODEL_SIZE"
TRANSCRIPTION_FASTER_WHISPER_TASK="transcribe"
TRANSCRIPTION_FASTER_WHISPER_COMPUTE_TYPE="float16"
TRANSCRIPTION_FASTER_WHISPER_BATCHING="True"
TRANSCRIPTION_FASTER_WHISPER_BATCH_SIZE="32"
TRANSCRIPTION_FASTER_WHISPER_DEVICE="cuda"
TRANSCRIPTION_CONFIRM_WORDS_OFFSET="0.3"
TRANSCRIPTION_CONFIRM_WORDS_MAX_WORDS="50"
TRANSCRIPTION_CONFIRM_WORDS_CONFIRM_IF_OLDER_THEN="1.0"

TRANSLATION_SERVER_URL="http://translation-service:5000/translate"
EOF
)

# Generate the dev environment file
ENV_CONTENT_DEV=$(cat <<EOF
BBB_API_URL="https://$DOMAIN/bigbluebutton/api/"
BBB_API_SECRET="$SECRET"
BBB_API_SHA="SHA256"

BBB_CLIENT_URL="https://$DOMAIN/html5client/"
BBB_CLIENT_WS="wss://$DOMAIN/html5client/websocket"

BBB_PAD_URL="https://$DOMAIN/pad/"
BBB_PAD_WS="wss://$DOMAIN/pad/"

BBB_WEBRTC_WS="wss://$DOMAIN/bbb-webrtc-sfu"

CHANGESET_EXTERNAL="true"
CHANGESET_HOST="localhost"
CHANGESET_PORT="50051"

TRANSCRIPTION_SERVER_HOST="0.0.0.0"
TRANSCRIPTION_SERVER_EXTERNAL_HOST="localhost"
TRANSCRIPTION_SERVER_PORT_TCP="5000"
TRANSCRIPTION_SERVER_PORT_UDP="5001"
TRANSCRIPTION_SERVER_SECRET="your_secret_token"
TRANSCRIPTION_SERVER_HEALTH_CHECK_PORT="8001"
TRANSCRIPTION_SERVER_PROMETHEUS_PORT="2112"
TRANSCRIPTION_AUDIO_BUFFER_LAST_N_SECONDS="30"
TRANSCRIPTION_AUDIO_BUFFER_MIN_N_SECONDS="1"
TRANSCRIPTION_RATE_LIMITER_FLOWRATE_PER_SECOND="2.0"
TRANSCRIPTION_CONVERT_AUDIO_CONVERT_SAMPLE_RATE="16000"
TRANSCRIPTION_VAD_DEVICE="cuda"
TRANSCRIPTION_VAD_MODEL_PATH="../.models/vad-whisperx"
TRANSCRIPTION_VAD_MAX_CHUNK_SIZE="30.0"
TRANSCRIPTION_VAD_LAST_TIME_SPOKEN_OFFSET="3"
TRANSCRIPTION_VAD_ONSET="0.500"
TRANSCRIPTION_VAD_OFFSET="0.363"
TRANSCRIPTION_VAD_USE_AUTH_TOKEN=""
TRANSCRIPTION_VAD_MODEL_FP=""
TRANSCRIPTION_VAD_SEGMENTATION_URL="https://whisperx.s3.eu-west-2.amazonaws.com/model_weights/segmentation/0b5b3216d60a2d32fc086b47ea8c67589aaeb26b7e07fcbe620d6d0b83e209ea/pytorch_model.bin"
TRANSCRIPTION_FASTER_WHISPER_MODEL_PATH="../.models/faster-whisper"
TRANSCRIPTION_FASTER_WHISPER_MODEL_SIZE="$WHISPER_MODEL_SIZE"
TRANSCRIPTION_FASTER_WHISPER_TASK="transcribe"
TRANSCRIPTION_FASTER_WHISPER_COMPUTE_TYPE="float16"
TRANSCRIPTION_FASTER_WHISPER_BATCHING="True"
TRANSCRIPTION_FASTER_WHISPER_BATCH_SIZE="32"
TRANSCRIPTION_FASTER_WHISPER_DEVICE="cuda"
TRANSCRIPTION_CONFIRM_WORDS_OFFSET="0.3"
TRANSCRIPTION_CONFIRM_WORDS_MAX_WORDS="50"
TRANSCRIPTION_CONFIRM_WORDS_CONFIRM_IF_OLDER_THEN="1.0"

TRANSLATION_SERVER_URL="http://localhost:8000/translate"
EOF
)

# Generate the docker dev file
ENV_CONTENT_DEV_DOCKER=$(cat <<EOF
BBB_API_URL="https://$DOMAIN/bigbluebutton/api/"
BBB_API_SECRET="$SECRET"
BBB_API_SHA="SHA256"

BBB_CLIENT_URL="https://$DOMAIN/html5client/"
BBB_CLIENT_WS="wss://$DOMAIN/html5client/websocket"

BBB_PAD_URL="https://$DOMAIN/pad/"
BBB_PAD_WS="wss://$DOMAIN/pad/"

BBB_WEBRTC_WS="wss://$DOMAIN/bbb-webrtc-sfu"

CHANGESET_EXTERNAL="true"
CHANGESET_HOST="changeset-service"
CHANGESET_PORT="50051"

TRANSCRIPTION_SERVER_HOST="0.0.0.0"
TRANSCRIPTION_SERVER_EXTERNAL_HOST="transcription-service"
TRANSCRIPTION_SERVER_PORT_TCP="5000"
TRANSCRIPTION_SERVER_PORT_UDP="5001"
TRANSCRIPTION_SERVER_SECRET="your_secret_token"
TRANSCRIPTION_SERVER_HEALTH_CHECK_PORT="8001"
TRANSCRIPTION_SERVER_PROMETHEUS_PORT="2112"
TRANSCRIPTION_AUDIO_BUFFER_LAST_N_SECONDS="30"
TRANSCRIPTION_AUDIO_BUFFER_MIN_N_SECONDS="1"
TRANSCRIPTION_RATE_LIMITER_FLOWRATE_PER_SECOND="2.0"
TRANSCRIPTION_CONVERT_AUDIO_CONVERT_SAMPLE_RATE="16000"
TRANSCRIPTION_VAD_DEVICE="cuda"
TRANSCRIPTION_VAD_MODEL_PATH="/app/.models/vad-whisperx"
TRANSCRIPTION_VAD_MAX_CHUNK_SIZE="30.0"
TRANSCRIPTION_VAD_LAST_TIME_SPOKEN_OFFSET="3"
TRANSCRIPTION_VAD_ONSET="0.500"
TRANSCRIPTION_VAD_OFFSET="0.363"
TRANSCRIPTION_VAD_USE_AUTH_TOKEN=""
TRANSCRIPTION_VAD_MODEL_FP=""
TRANSCRIPTION_VAD_SEGMENTATION_URL="https://whisperx.s3.eu-west-2.amazonaws.com/model_weights/segmentation/0b5b3216d60a2d32fc086b47ea8c67589aaeb26b7e07fcbe620d6d0b83e209ea/pytorch_model.bin"
TRANSCRIPTION_FASTER_WHISPER_MODEL_PATH="/app/.models/faster-whisper"
TRANSCRIPTION_FASTER_WHISPER_MODEL_SIZE="$WHISPER_MODEL_SIZE"
TRANSCRIPTION_FASTER_WHISPER_TASK="transcribe"
TRANSCRIPTION_FASTER_WHISPER_COMPUTE_TYPE="float16"
TRANSCRIPTION_FASTER_WHISPER_BATCHING="True"
TRANSCRIPTION_FASTER_WHISPER_BATCH_SIZE="32"
TRANSCRIPTION_FASTER_WHISPER_DEVICE="cuda"
TRANSCRIPTION_CONFIRM_WORDS_OFFSET="0.3"
TRANSCRIPTION_CONFIRM_WORDS_MAX_WORDS="50"
TRANSCRIPTION_CONFIRM_WORDS_CONFIRM_IF_OLDER_THEN="1.0"

TRANSLATION_SERVER_URL="http://translation-service:5000/translate"
EOF
)

create_file_if_not_exists ".env" "$ENV_CONTENT"
create_file_if_not_exists ".env-dev" "$ENV_CONTENT_DEV"
create_file_if_not_exists ".env-dev-docker" "$ENV_CONTENT_DEV_DOCKER"